use_frameworks!

platform :ios, '9.0'

target 'PLVImagePickerController_Example' do
  pod 'PLVImagePickerController', :path => '../'

  target 'PLVImagePickerController_Tests' do
    inherit! :search_paths

    
  end
end
